Feat/acc dash
Livinng/dashboard pull request #1
Opened 2023-07-19 16:13 UTC by LucasChanquia

Buenas! Se añade el componente sideBar y la carpeta public con sus respectivos archivos svg. Saludos!

2023-07-19 16:31 UTC, LucasChanquia commented
Listo el cambio estiven

2023-07-20 03:15 UTC, devEstivenValencia requested changes
Teniendo en cuenta el como trabajaremos las rutas del Host y del Admin tendremos que hacer unos cambios y es que si revisas el figma, el menu de la sidebar varia dependiendo de si eres admin o host.

Por lo tanto deben de haber 2 variantes de SideBar una **SideBarHost** y otra **SideBarAdmin**

Recuerda guardar estos components en su respectiva carpeta components dentro de la carpeta app

2023-07-20 14:18 UTC, devEstivenValencia approved these changes
All ok

2023-07-20 14:19 UTC, devEstivenValencia commented
All ok

2023-07-20 14:20 UTC, merged